id: com.visualstudio.code.tool.docker-compose
branch: '23.08'
build-extension: true
sdk: org.freedesktop.Sdk//23.08
runtime: com.visualstudio.code
runtime-version: stable
separate-locales: false
appstream-compose: false
sdk-extensions:
  - org.freedesktop.Sdk.Extension.golang
build-options:
  append-path: /usr/lib/sdk/golang/bin
  prefix: /app/tools/docker-compose
  strip: true
cleanup: []
modules:
  - name: docker-compose
    buildsystem: simple
    build-commands:
      - make DESTDIR=./bin build
      - install -Dm755 bin/docker-compose -t ${FLATPAK_DEST}/bin/
    sources:
      - type: git
        url: https://github.com/docker/compose.git
        tag: v2.29.2
        commit: 234036756b94e296b6ff4dc4d54896993b60db36
        x-checker-data:
          type: json
          url: https://api.github.com/repos/docker/compose/releases/latest
          tag-query: .tag_name
          timestamp-query: .published_at
          version-query: $tag | sub("^v"; "")
      - go.mod.yml

  - name: bundle-setup
    buildsystem: simple
    build-commands:
      - install -Dm644 -t $FLATPAK_DEST/share/metainfo $FLATPAK_ID.metainfo.xml
      - appstream-compose --basename=$FLATPAK_ID --prefix=$FLATPAK_DEST --origin=flatpak
        $FLATPAK_ID
    sources:
      - type: file
        path: com.visualstudio.code.tool.docker-compose.metainfo.xml
